security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 13

    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
                property: username

        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern: ^/
            form_login:
                provider: our_db_provider
                login_path: /login
                check_path: /login_check
                default_target_path: /app/example
            logout:
                path: /logout
                target: /app/example
            anonymous: true

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/create, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/app/example, roles: IS_AUTHENTICATED_ANONYMOUSLY }